config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  resources :users, only: %i( new create show edit update )
  resources :sessions, only: %i( new create destroy )
  resources :favorites, only: %i( create destroy show )
  resources :photos do
    collection do
      post :confirm
    end
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :image, ImageUploader

  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 }, format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  validates :email, uniqueness: true

  before_validation {email.downcase!}

  has_secure_password
  validates :password, length: { minimum: 6 }, on: :create

  has_many :photos
  has_many :favorites, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
  before_action :login_required

  private

  def login_required
    redirect_to new_session_path unless current_user
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i( show edit update destroy)

  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.contact_mail(@contact).deliver
      redirect_to contacts_path, notice: 'Contact was successfully created'
    else
      render :new
    end
  end

  private

  def set_contact
    @contact = Contact.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:name, :email, :content)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :set_photo, only: %i[ show ]

  def create
    favorite = current_user.favorites.create(photo_id: params[:photo_id])
    redirect_to photos_path, notice: "#{favorite.photo.user.name}さんのフォトをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to photos_path, notice: "#{favorite.photo.user.name}さんのフォトをお気に入り解除しました"
  end

  def show
    @favorite = current_user.favorites.where(user_id: current_user.id)
  end
  
  private

  def set_photo
    @photo = Photo.find(params[:id])
  end

end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: %i[ show edit update destroy ]
  # GET /photos or /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1 or /photos/1.json
  def show
    @favorite = current_user.favorites.find_by(photo_id: @photo.id)
  end

  # GET /photos/new
  def new
    if params[:back]
      @photo = Photo.new(photo_params)
    else
      @photo = Photo.new
    end
  end

  # GET /photos/1/edit
  def edit
    if @photo.user_id != current_user.id
      redirect_to photos_path
    end
  end

  def confirm
    @photo = current_user.photos.build(photo_params)
    render :new if @photo.invalid?
  end

  # POST /photos or /photos.json
  def create
    @photo = current_user.photos.build(photo_params)
    respond_to do |format|
      if @photo.save
        PhotoMailer.photo_mail(@photo).deliver
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully created." }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1 or /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to photo_url(@photo), notice: "Photo was successfully updated." }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1 or /photos/1.json
  def destroy
    if @photo.user_id == current_user.id
      @photo.destroy
        respond_to do |format|
          format.html { redirect_to photos_url, notice: "Photo was successfully destroyed." }
          format.json { head :no_content }
        end
    else
      redirect_to photos_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_photo
    @photo = Photo.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def photo_params
    params.require(:photo).permit(:content, :image, :image_cache)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: %i( new create )
  
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to photos_path
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: %i( new create )

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id), notice: "プロフィールを編集しました"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :content, :image, :image_cache)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_photos_path
    elsif action_name == 'edit'
      photo_path
    end
  end
end


app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    current_user.present?
  end
end

app/views/favorites/show.html.erb
<h1>お気に入り一覧</h1>

<main>
<% @favorite.each do |favorite| %>
  <table class="contents">
    <tbody class="content">
      <tr>
        <tr><td><%= favorite.user.name %></td></tr>
        <tr><td><%= favorite.photo.content %></td></tr>
        <tr><td><%= image_tag favorite.photo.image.url if favorite.photo.image && favorite.photo.image.url %></td></tr>
        <tr><td><%= favorite.user.updated_at.strftime('%Y/%m/%d %H:%M') %></td></tr>
        <td><%= link_to 'Show', photo_path(favorite.photo.id) %></td>
      </tr>
    </tbody>
  </table>
<% end %>
</main>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoSharingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <% if logged_in? %>
        <button type="button" class="btn btn-light"><%= link_to "Profile", user_path(current_user.id) %></button>
        <button type="button" class="btn btn-light"><%= link_to "Index", photos_path %></button>
        <button type="button" class="btn btn-light"><%= link_to "Log out", session_path(current_user.id), method: :delete %></button>
      <% else %>
        <button type="button" class="btn btn-light"><%= link_to "Sign up", new_user_path %></button>
        <button type="button" class="btn btn-light"><%= link_to "Log in", new_session_path %></button>
      <% end %>
    </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>

    <%= yield %>

    <footer>
      <p>photo_sharing_app</p>
    </footer>
  </body>
</html>

app/views/photos/_form.html.erb
<%= form_with(model: photo, local: true, url: choose_new_or_edit) do |form| %>
  <% if photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
        <% photo.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="contents">
  <tbody class="content">
      <div class="field">
        <tr>
          <td><%= form.label :content %></td>
        </tr>
        <tr>
          <td><%= form.text_area :content %></td>
        </tr>
      </div>
    
      <div class="field">
        <tr>
          <td><%= form.label :image %></td>
        </tr>
        <tr>
          <td><%= image_tag(@photo.image.url) if @photo.image && @photo.image.url %></td>
        </tr>
        <tr>
          <td><%= form.file_field :image %></td>
          <td><%= form.hidden_field :image_cache %></td>
        </tr>
      </div>
    </tbody>
  </table>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/photos/confirm.html.erb
<h1>確認画面</h1>

<%= form_with(model: @photo, url: photos_path, local: true) do |form| %>
  <table class="contents">
    <tbody class="content">
      <tr><td><%= form.hidden_field :content %><td></tr>
      <tr><td><p>Content：<%= @photo.content %></p></td></tr>
      <tr><td><%= image_tag(@photo.image.url) if @photo.image && @photo.image.url %></td></tr>
      <tr><td><%= form.hidden_field :image_cache %></td></tr>
    </tbody>
  </table>
  <%= form.submit "投稿する" %>
<% end %>


<%= form_with(model: @photo, url:new_photo_path, local:true, method:"get") do |form| %>
  <%= form.hidden_field :image_cache %>
  <%= form.hidden_field :content %>
  <%= form.submit "戻る", name: "back" %>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<button type="button" class="btn btn-light"><%= link_to 'New Photo', new_photo_path %></button>

<main>
<% @photos.each do |photo| %>
  <table class="conntents">
    <tbody class="content">
    <tr><th><%= photo.user.name %></th></tr>
    <tr><td><%= photo.content %></td></tr>
    <tr><td><%= image_tag photo.image.url if photo.image && photo.image.url %></td></tr>
    <tr><td><%= photo.updated_at.strftime('%Y/%m/%d %H:%M') %></td></tr>
    <tr>
      <td colspan="3"><%= link_to 'Show', photo %>
      <% if photo.user_id == current_user.id %>
        <%= link_to 'Edit', edit_photo_path(photo) %>
        <%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
      </td>
    </tr>
    </tbody>
  </table>
<% end %>
</main>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<table class="contents">
  <tbody class="content">
    <tr><td><strong><%= @photo.user.name %></strong></td></tr>
    <tr><td><p><%= @photo.content %></p></td></tr>
    <td><p><%= image_tag @photo.image.url if @photo.image && @photo.image.url %></p></td>
    <td>
    <% if @photo.user_id == current_user.id %>
      <%= link_to 'Edit', edit_photo_path(@photo) %>
    <% end %>
    </td>
    <tr><td><%= @photo.updated_at.strftime('%Y/%m/%d %H:%M') %></td></tr>
  </tbody>
</table>

<% unless @photo.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= button_to "お気に入り解除する", favorite_path(id: @favorite.id), method: :delete %>
  <% else %>
    <%= button_to "お気に入りする", favorites_path(photo_id: @photo.id), method: :post %>
  <% end %>
<% end %>

<%= link_to 'Back', photos_path %>

app/views/users/edit.html.erb
<h1>プロフィール編集ページ</h1>

<%= form_with(model: @user, url: user_path, local: true, method: :patch) do |form| %>
  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.text_field :email %>
  
  <%= form.label :content %>
  <%= form.text_field :content %>

  <%= form.label :image %>
  <%= form.file_field :image %>
  <%= form.hidden_field :image_cache %>

  <%= form.submit %>
<% end %>

<%= link_to 'Back', user_path(@user.id) %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_with(model: @user, local: true) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %>prohibited this <%= @user.name %>from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.label :name %>
  <%= form.text_field :name %>

  <%= form.label :email %>
  <%= form.text_field :email %>

  <%= form.label :password %>
  <%= form.password_field :password %>

  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>

  <%= form.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>

<p>メールアドレス：<%= @user.email %></p>
<p>自己紹介：<%= @user.content %></p>
<p>画像：<%= image_tag @user.image.url if @user.image.url %></p>

<%= link_to 'favorite', favorite_path %>
<% if @user.id == current_user.id %>
  <%= link_to 'Edit', edit_user_path(@user) %>
<% end %>